name: Build osx

on:
  push:
    branches-ignore:
      - 'rotatrix/**'
    tags-ignore:
      - '*-rotatrix.*'
  workflow_dispatch:

jobs:
  build_osx:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_osx.yml@legacy
    secrets: inherit
    with:
      actions_branch: legacy
