name: Build flatpak

on:
  push:
    branches-ignore:
      - rotatrix-prusaslicer-2.9.6
  workflow_dispatch:

jobs:
  build_flatpak:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_flatpak.yml@legacy
    secrets: inherit
    with:
      actions_branch: legacy
