name: Build flatpak

on:
  push:
    branches-ignore:
      - 'rotatrix/**'
    tags-ignore:
      - '*-rotatrix.*'
  workflow_dispatch:

jobs:
  build_flatpak:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_flatpak.yml@legacy
    secrets: inherit
    with:
      actions_branch: legacy
