name: Build osx

on:
  push:
    branches-ignore:
      - rotatrix-prusaslicer-2.9.6
  workflow_dispatch:

jobs:
  build_osx:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_osx.yml@legacy
    secrets: inherit
    with:
      actions_branch: legacy
