name: Build flatpak

on:
  push:
    branches-ignore:
      - rotatrix
      - 'rotatrix/**'
    tags:
      - 'version_*'
      - '!*-rotatrix.*'
  workflow_dispatch:
    inputs:
      enable_sentry:
        description: 'Enable sentry'
        default: false
        type: boolean
      release_build:
        description: 'Release build'
        default: false
        type: boolean
      debug_symbols:
        description: 'Debug symbols'
        default: false
        type: boolean

jobs:
  build_flatpak:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_flatpak.yml@master
    secrets: inherit
    with:
      actions_branch: master
      enable_sentry: ${{ inputs.enable_sentry || false }}
      release_build: ${{ inputs.release_build || startsWith(github.ref, 'refs/tags/version_') }}
      debug_symbols: ${{ inputs.debug_symbols || false }}
