name: Run clang-format

on:
  push:
    branches-ignore:
      - rotatrix
      - 'rotatrix/**'
  workflow_dispatch:

jobs:
  formatting_check:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/clang_format.yml@master
    secrets: inherit
    with:
      actions_branch: master

